spring:
  thymeleaf:
    cache: false
    enabled: true
  application:
    name: "GitHub Reader"

management:
  endpoint:
    beans:
      enabled: true
    metrics:
      enabled: true
    health:
      showDetails: "always"
  server:
    port: 9001
    servlet:
      contextPath: "/"
  endpoints:
    web:
      exposure:
        include: "*"